{
  lib,
  buildPythonPackage,
  fetchFromGitHub,

  # build-system
  hatchling,
  uv-dynamic-versioning,

  # dependencies
  cyclopts,
  pydantic,
  rich,

  # tests
  pytest-asyncio,
  pytest-timeout,
  pytestCheckHook,
}:

buildPythonPackage (finalAttrs: {
  pname = "prefab-ui";
  version = "0.19.1";
  pyproject = true;

  __structuredAttrs = true;

  src = fetchFromGitHub {
    owner = "PrefectHQ";
    repo = "prefab";
    tag = "v${finalAttrs.version}";
    hash = "sha256-caSsMR6Il4D1l9Y1ScdN5HZ4TPG2YyB6JzctDt+W3WE=";
  };

  build-system = [
    hatchling
    uv-dynamic-versioning
  ];

  dependencies = [
    cyclopts
    pydantic
    rich
  ];

  nativeCheckInputs = [
    pytest-asyncio
    pytest-timeout
    pytestCheckHook
  ];

  disabledTestPaths = [
    # Requires Deno/Pyodide WASM runtime which is not in nixpkgs
    "tests/test_sandbox.py"
    # Reads renderer/schemas/ fixture files generated by tools/generate_schemas.py,
    # which are not present in the source tree
    "tests/test_contract.py"
  ];

  pythonImportsCheck = [ "prefab_ui" ];

  meta = {
    description = "The generative UI framework that even humans can use";
    homepage = "https://github.com/PrefectHQ/prefab";
    changelog = "https://github.com/PrefectHQ/prefab/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.asl20;
    maintainers = with lib.maintainers; [ squat ];
    mainProgram = "prefab";
  };
})
